[features]
seeds = true
skip-lint = false
[programs.localnet]
predtict_safroon = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "C:\\Users\\user\\.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
[workspace]
types = "Prediction-safroon/programs/Prediction-safroon/src/"
